# version: '2'
#
# services:
#   db:
#     postgres:
#       image: postgres:9.4
#       volumes:
#         - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
#
#   api:
#     build:
#       context: .
#       dockerfile: provision/Dockerfile
#     ports:
#       - "3000:3000"
#     links:
#       - db
